[book]
title = "Rust в примери"
description = "Rust в примери (RВП) представлява набор от работещи примери, онагледяващи различни понятия и стандартни библиотеки в Rust."
author = "Общността на Rust"

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = true

[output.html.fold]
enable = false

[output.html]
git-repository-url = "https://github.com/kberov/rust-by-example-bg"

[rust]
edition = "2021"
